
spring:
  application:
    name: monitor-estudos
  datasource:
    url: jdbc:postgresql://localhost:5433/tracker_estudos
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: America/Sao_Paulo
